name: Slither

on:
  push:
    branches: [main]

jobs:
  slither:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install submodules
        run: git submodule update --init --recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install setuptools
        run: python -m pip install --upgrade pip setuptools

      - name: Install Slither
        run: pip install slither-analyzer

      - name: Install solc-select
        run: |
          pip install solc-select
          solc-select install 0.8.26
          solc-select use 0.8.26

      - name: Run Slither
        run: slither "contracts/v1/HeaderProtocol.sol" --exclude-informational
